### ISSUE TITLE
Plugin incompatible with new IntelliJ 2020.1EAP

### ISSUE THREAD

**Issue by kool79** [kkowalski/intellij-circleci#17]
It is not loaded into Plugins.

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.5616.10, built on February 19, 2020
IntelliJ IDEA EAP User

**Comment by kkowalski** [comment]
It's in alpha channel for now. Hopefully in a week or two I'll move it to stable.

**Comment by kool79** [comment]
I added alpha cjannel to my IDE (https://plugins.jetbrains.com/plugins/alpha/13690) but it still not here. On [plugin page](https://plugins.jetbrains.com/plugin/13690-circleci/versions) version interval is defined as 2019.3.1 — 2019.3.3
Can you please publish (to alpha channel) version with extended interval (until-build="201.*")? I want to try it IntelliJ EAP version (2020.1) (It can be changes in plugin.xml)

**Comment by kkowalski** [comment]
Pushed to stable channel and compatible with latest
